databases:
  - name: ecomm_l52b_3bq7
    databaseName: ecomm_l52b_3bq7
    user: ecomm_l52b_3bq7_user
    plan: free

services:
  - type: web
    name: ecomm_l52b_3bq7
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: postgres://ecomm_l52b_3bq7_user:rOeNvWVRuoz5w7RMyMmwSD2dLiNelUHh@dpg-co58bu21hbls73ce3n80-a/ecomm_l52b_3bq7
        fromDatabase:
          name: ecomm_l52b_3bq7
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: 2,
        value: 2 # sensible default